package online.qsx.model;

import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.vocation
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    private String vocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.hobby
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.createdate
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.vocation
     *
     * @return the value of user.vocation
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public String getVocation() {
        return vocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.vocation
     *
     * @param vocation the value for user.vocation
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public void setVocation(String vocation) {
        this.vocation = vocation == null ? null : vocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.hobby
     *
     * @return the value of user.hobby
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.hobby
     *
     * @param hobby the value for user.hobby
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.createdate
     *
     * @return the value of user.createdate
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.createdate
     *
     * @param createdate the value for user.createdate
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    public User(Integer id, String username, String vocation, String email, String gender, String hobby, Date birthday, Date createdate, String password) {
        this.id = id;
        this.username = username;
        this.vocation = vocation;
        this.email = email;
        this.gender = gender;
        this.hobby = hobby;
        this.birthday = birthday;
        this.createdate = createdate;
        this.password = password;
    }

    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public User(String username, String vocation, String email, String gender, String hobby, Date birthday, String password) {
        this.username = username;
        this.vocation = vocation;
        this.email = email;
        this.gender = gender;
        this.hobby = hobby;
        this.birthday = birthday;
        this.password = password;
    }


    public User(Integer id) {
        this.id = id;
    }

    public User() {

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Jan 15 19:18:46 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", vocation=").append(vocation);
        sb.append(", email=").append(email);
        sb.append(", gender=").append(gender);
        sb.append(", hobby=").append(hobby);
        sb.append(", birthday=").append(birthday);
        sb.append(", createdate=").append(createdate);
        sb.append(", password=").append(password);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}